version: '3.7'

services:
  db:
    container_name: byom-db
    image: mariadb:10.5.5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql

  php:
    container_name: byom-php
    build: 
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000'
    volumes:
      - ./app/api:/www
      - ${LOCAL_STORAGE_PATH}/:/local
      - ./docker/php/conf.d/docker-php-ram-limit.ini:/usr/local/etc/php/conf.d/docker-php-ram-limit.ini
    depends_on:
      - db

  nginx:
    container_name: byom-nginx
    image: nginx:stable-alpine
    ports:
      - '8403:80'
    volumes:
      - ./app/api:/www
      - ${LOCAL_STORAGE_PATH}/:/local
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  node:
    container_name: byom-node
    build: 
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./app/web:/root
      - /root/node_modules
    depends_on:
      - nginx

volumes:
  db-data:
