version: '3.7'

services:
  db:
    container_name: byom-db
    image: mariadb:10.5.5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql

  php:
    container_name: byom-php
    build: 
      context: .
      dockerfile: docker/php/prod.Dockerfile
    ports:
      - '9000'
    volumes:
      - ./api:/www
      - ${LOCAL_STORAGE_PATH}/:/local
      - ./docker/php/conf.d/docker-php-ram-limit.ini:/usr/local/etc/php/conf.d/docker-php-ram-limit.ini
    depends_on:
      - db

  nginx:
    container_name: byom-nginx
    image: nginx:stable-alpine
    ports:
      - '${API_PORT}:80'
    volumes:
      - ./api:/www
      - ${LOCAL_STORAGE_PATH}/:/local
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  node:
    container_name: byom-node
    build:
      context: .
      dockerfile: docker/node/prod.Dockerfile
    environment:
      - VITE_API_PORT=${API_PORT}
      - VITE_WEB_PORT=${WEB_PORT}
    ports:
      - '${WEB_PORT}:3000'
    volumes:
      - ./web:/app
    depends_on:
      - nginx

volumes:
  db-data:
