version: '3.7'

services:
  php:
    build: 
      context: .
      dockerfile: docker/php/prod.Dockerfile

  node:
    container_name: byom-node
    build:
      context: .
      dockerfile: docker/node/prod.Dockerfile
    environment:
      - VITE_API_PORT=${API_PORT}
      - VITE_WEB_PORT=${WEB_PORT}
    ports:
      - '${WEB_PORT}:3000'
    volumes:
      - ./web:/root
      - /root/build
      - /root/.svelte-kit
      - /root/node_modules
    depends_on:
      - nginx
