version: '3.7'

services:
  php:
    container_name: byom-php
    build: 
      context: .
      dockerfile: docker/php/prod.Dockerfile
    ports:
      - '9000'
    volumes:
      - ./api:/www
      - ${LOCAL_STORAGE_PATH}/:/local
      - ./docker/php/conf.d/docker-php-ram-limit.ini:/usr/local/etc/php/conf.d/docker-php-ram-limit.ini
    depends_on:
      - db

  node:
    container_name: byom-node
    build:
      context: .
      dockerfile: docker/node/prod.Dockerfile
    environment:
      - VITE_API_PORT=${API_PORT}
      - VITE_WEB_PORT=${WEB_PORT}
    ports:
      - '${WEB_PORT}:3000'
    volumes:
      - ./web:/root
    depends_on:
      - nginx

volumes:
  db-data:
