version: '3.7'

services:
  db:
    container_name: byom-db
    image: mariadb:10.5.5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql

  php:
    container_name: byom-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000'
    volumes:
      - app-public:/www/public
      - ./api:/www
      - ./docker/php/conf.d/docker-php-ram-limit.ini:/usr/local/etc/php/conf.d/docker-php-ram-limit.ini
      - ${LOCAL_STORAGE_PATH}/:/local
      - /www/var
      - /www/vendor
    depends_on:
      - db

  nginx:
    container_name: byom-nginx
    image: nginx:stable-alpine
    ports:
      - '${API_PORT}:80'
    volumes:
      - app-public:/www/public
      - ./api:/www
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ${LOCAL_STORAGE_PATH}/:/local
    depends_on:
      - php

volumes:
  db-data:
  app-public:
